# Generated by Django 4.1.1 on 2022-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asxssdf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
